[workspace]
members = ["audido-core", "audido-macros", "audido-tui"]
default-members = ["audido-tui"]
resolver = "2"

[workspace.package]
version = "0.1.2"
edition = "2024"
license = "GPL-3.0-or-later"
repository = "https://github.com/nazhifhaidarputra/audido"

[workspace.dependencies]
anyhow = "1.0.104"
tokio = { version = "1.53.0", features = ["full"] }
log = "0.4.30"
tempfile = "3.27.0"
reqwest = "0.13"
futures = "0.3.34"
ctor = "1.0.13"
env_logger = "0.11"
